### ISSUE TITLE
Реализовать групповые операции и Select

### ISSUE THREAD

**Issue by k-alexandrovsky** [aurusov/raox#1]
Добавить групповые операции и `Select` в кодогенератор (`ExpressionCompiler`), добавить сам `Select` в грамматику

**Comment by k-alexandrovsky** [comment]
https://github.com/k-alexandrovsky/rdo-xtext/commit/4c14120f1b54621a8735d5922b5921a1a83ee3bd, https://github.com/k-alexandrovsky/rdo-xtext/commit/fd7de0c49fe7cd88c9f57b1d0a6c8c6443e41145

**Comment by k-alexandrovsky** [comment]
Пример кода:

``` java

if (
    rdo_lib.Select.Exist(
        barber.Клиенты.getManager().getAll(),
        new rdo_lib.Select.Checker<barber.Клиенты>()
        {
            @Override
            public boolean check(barber.Клиенты current)
            {
                return true && current.тип == barber.Клиенты.тип_enum.Тип2;
            }
        }
    ))
    do_smth();
```

**Comment by aurusov** [comment]
Выглядит просто.
