### ISSUE TITLE
Листы курсового проекта

### ISSUE THREAD

**Issue by k-alexandrovsky** [aurusov/raox#10]
@aurusov 
1. Лист постановки задачи
   http://k-alexandrovsky.github.io/course_prj_10/intro.pdf
2. Диаграмма пакетов Xtext и стейтчарт-диаграмма процесса разработки имитационной модели
   http://k-alexandrovsky.github.io/course_prj_10/package_and_activity.pdf
3. Диаграммы синтаксиса (грамматика)
   http://k-alexandrovsky.github.io/course_prj_10/syntax_1.pdf
   http://k-alexandrovsky.github.io/course_prj_10/syntax_2.pdf
4. Диаграмма классов получившегося симулятора (весь пакет rdo_lib)
   http://k-alexandrovsky.github.io/course_prj_10/simulator.pdf
5. Лист результатов (еще не доделанный)
   http://k-alexandrovsky.github.io/course_prj_10/outro.pdf

**Comment by aurusov** [comment]
1. Нужен штамп.
2. ok
3. ok (2 x A1)
4. ok
5. Нужно доделать, понятно что.

**Comment by k-alexandrovsky** [comment]
Update

1 Штампы:
http://k-alexandrovsky.github.io/course_prj_10/stamps.pdf

5 Лист результатов:
http://k-alexandrovsky.github.io/course_prj_10/outro.pdf

**Comment by aurusov** [comment]
Круто. Все листы на печать. Теперь жду ТЗ на проверку.

**Comment by k-alexandrovsky** [comment]
Записка
http://k-alexandrovsky.github.io/course_prj_10/note.pdf

**Comment by aurusov** [comment]
> Основная цель работы – создание многофункциональной среды разработки, способной создавать и запускать имитационные модели на языке РДО

Часто слово создавать. Замени одно из них на разрабатывать. Не забудь поменять титульник.

**Comment by aurusov** [comment]
> MacOS и Linux

**или**

**Comment by aurusov** [comment]
Исправь и на печать.

**Comment by k-alexandrovsky** [comment]
> Часто слово создавать. Замени одно из них на разрабатывать. Не забудь поменять титульник.

Сделаю не "создавать модели", а "редактировать". Тогда вообще все слова будут разными
