### ISSUE TITLE
Интегрировать запуск моделей в Eclipse

### ISSUE THREAD

**Issue by k-alexandrovsky** [aurusov/raox#11]
Блокирует:
- [x] #12 
- [x] #14 
- [ ] #15

<hr>

Генерация кода Xtext'ом, конечно же, в Eclips'е, а вот запуск получившегося java-приложения сейчас - отдельно. Надо интегрировать. Запуск генерации отдельной кнопкой, запуск модели еще одной, Eclipse должен контролировать процесс.

**Comment by k-alexandrovsky** [comment]
@aurusov 

Удалось добиться запуска модели из эклипса в одно нажатие. Метод пока очень простой, он просто лезет на диск в папку проекта, динамически подгружает сгенерированный и скомпилированный класс, подменяет ему консоль, и дергает `main`. Результат на скриншоте.

![rdoexec2](https://cloud.githubusercontent.com/assets/6878143/3251950/569a365c-f1b9-11e3-8f29-3933ed911928.png)

Из не очень понятных в плане реализации моментов есть синхронизация процесса 
`генерация кода` &rarr; `компиляция классов` &rarr; `запуск модели на исполнение`.
Все эти действия делают совершенно разные сущности (xtext, eclipse java compiler и мой код соответственно), поэтому как их подружить, и как узнать, что модель уже можно запускать, мне пока непонятно. Однако у модели теперь однозначно должен быть другой main, которому надо будет скармливать инстанс трейсера, или вообще какой то общий интерфейс взаимодействия с моделью, запускать это все в отдельном потоке (сейчас я блокирую ui тред) и так далее.

**Comment by k-alexandrovsky** [comment]
@aurusov
Появилась небольшая проблема с UI. Суть примерно в следующем - помимо кнопок запуска моделей и ползунка скорости в интерфейсе еще должна быть строка статуса, где будет отображаться текущее время, масштаб моделирования, все что угодно, в общем. В РДО она была внизу, что довольно логично. В эклипсе с этим возникла проблема. Из-за того, что система размещения тулбаров у них очень забагованная, сейчас я могу предложить следующие варианты (текст для примера, вообще там должно быть модельное время):
1. Засунуть его наверх (некрасиво и нелогично)
![image](https://cloud.githubusercontent.com/assets/6878143/4692906/1b71a3c6-5780-11e4-8e45-a5dd695fbc39.png)
2. Вниз и вправо (уже лучше, но все равно неудобно, слева будет периодически эклипсовский прогрессбар с компиляцией мигать к тому же)
![image](https://cloud.githubusercontent.com/assets/6878143/4692912/62c26fe4-5780-11e4-8c3f-1a80ca5f7f68.png)
3. Перед прогрессбаром (красиво и логично, но из за непонятного бага панель появляется лишь на второй запуск эклипса в каждом конкретном воркспейсе)
![image](https://cloud.githubusercontent.com/assets/6878143/4692921/a984ffbe-5780-11e4-99e9-7188a7f110e0.png)
4. Радикальный. Придумать отдельное окошко для этого
![image](https://cloud.githubusercontent.com/assets/6878143/4692950/c9724948-5781-11e4-9455-710a06e5549d.png)

**Comment by aurusov** [comment]
Можно попробовать 4-й. Кандидаты для вывода
- текущее модельное время (в Арене выводилось еще календарная дата от него)
- масштабный коэффициент для синхронизации
- коэффициент замедления
- потребляемая память
