### ISSUE TITLE
Каким образом реализовать SMR в проекте

### ISSUE THREAD

**Issue by k-alexandrovsky** [aurusov/raox#2]
to @aurusov 

Я вплотную подошел к необходимости реализации SMR в каком бы то ни было виде. У меня есть несколько вариантов, но мне ни один не нравится. Хотелось бы на этот счет посоветоваться.

Варианты:
- Сделать возможным описать блок SMR в любом месте модели наравне с другими объектами:
  
  ```
  RDOModel
      : objects += RDOEntity*
  ;
  
  RDOEntity
      : ResourceType   // RTP
      | Resources      // RSS
      | Sequence       // FUN-SEQ 
      | Constants      // FUN-CON
      | Function       // FUN-FUN
      | Pattern        // PAT & EVN
      | DecisionPoint  // DPT
      | Process        // PRC
  //  | Frame          // FRM
      | Results        // PMD
      | SimulationRun  // SMR
  ;
  ```
  
  Здесь необходимо будет еще проверять, в единственном ли экземпляре описан блок SMR
- Разделение грамматики на две ветки - модель **_или**_ SMR:
  
  ```
  RDOModel
      : objects += RDOEntity*
      | simulation = SimulationRun
  ;
  ```
- Отдельная грамматика для SMR, компилирующая файлы с одноименным расширением. Тут мне непонятно пока, насколько сложно будет подружить грамматики между собой, и как это все потом собирать воедино (ведь когда то это станет плагином)

**Comment by aurusov** [comment]
Я за первый.

**Comment by k-alexandrovsky** [comment]
@aurusov
Сделал первый вариант. Благодаря встроенной системе проверки одинаковых имен он не дает описать два SMR'а в одном файле. Но при этом в разных файлах дает. Однако писать валидатор для проверки нескольких файлов сразу - это надо перелопатить половину движка xtext'а. Плюс, если модель состоит из действительно большого количества независимых файлов, с точки зрения производительности тянуть валидацию всех сразу будет расточительно. Поэтому я решил добавить интерактива и спрашивать у пользователя во время генерации, какой SMR брать:
![18e695dea7faa23d51f77d6f3028bc32](https://cloud.githubusercontent.com/assets/6878143/2569202/48b4e33c-b8ea-11e3-863b-079a8c5867e9.png)
Подойдет ли такой вариант?

P.S. Если SMR один, то окошко не вылезет, соответственно. Могу сделать модальным, могу немодальным (вдруг пользователь захочет посмотреть на текст моделей перед выбором)

**Comment by aurusov** [comment]
Лучше сформировать сообщение об ошибке повторного использования SMR

**Comment by k-alexandrovsky** [comment]
https://github.com/k-alexandrovsky/rdo-xtext/commit/087fa7ed02b5c0fbb9776c1036086cf248ea1ec2

**Comment by aurusov** [comment]
Круто. Спозиционироваться на ошибке можно ?

**Comment by k-alexandrovsky** [comment]
Да, это такая же ошибка, как и остальные. Ее обрабатывает валидатор (то есть до генерации кода даже не доходит). Фишка в том, что для этого надо немного костыльным способом собрать все файлы (т.н. Resource'ы) и запросить у них список объектов (SimulationRun в нашем случае). Как мне кажется, это довольно ресурсоемкая операция, однако SMR в моделях пишется редко, редактируется редко, и валидируется, соответственно, тоже. Плюс валидация все равно идет фоновым потоком.
