### ISSUE TITLE
Название нового РДО

### ISSUE THREAD

**Issue by bogachev-pa** [aurusov/raox#24]
@k-alexandrovsky
Я тут оформляю курсач и не знаю, что писать, когда ссылаюсь на новое РДО, т.к. у него нет никакого конкретного названия. @aurusov предложил в качестве рабочего названия `rdox` (ну или `rdo-x`), что ты думаешь по этому поводу?

**Comment by k-alexandrovsky** [comment]
Я тут подумал, а может вообще как то от аббревиатуры отойти. Можем назвать совсем по-другому. Главное, чтобы так же хорошо запоминалось, как РДО. Просто проблема в том, что я недавно подходил сдавать дз заведующему кафедрой, он посмотрел на мои картины напряжений в зубчатых колесах, и спросил, что у меня в дипломе. Я и говорю - новое РДО (с акцентом на "новое"). Мне в ответ - "аа, снова парикмахерская". И мне стало обидно( что они прицепились к парикмахерской. Понятно, что трудно запомнить непонятные технические нюансы, тем более связанные с программированием, зато гораздо приятнее запомнить парикмахерскую. Видимо, надо было делать default модель "типичная СМО" с "заявками".

Возможно, это только он не любит РДО, и нам не нужен ребрендинг. Просто если мы хотим замутить GEF и вообще в итоге благодаря EMF модульность получше даже, чем у anylogic, то может быть и стоит затевать, не знаю. `rdox` хорошо, но вот уже навскидку: https://github.com/RebelProject/RDox. `rdo-x` тоже хорошо. Просто я понимал логику изменения расширения проекта `rdo -> rdox`. Это как у MS Office, формат стал лучше, избавился от старых непонятных костылей, везде XML, красота. А у названий софтин `X` обычно означает версию (типа OS X, MPLAB X и т.д.), но мы же не Firefox, чтобы так мажорными версиями разбрасываться.

**Comment by k-alexandrovsky** [comment]
Кстати, прошу любить и жаловать новую старую фичу)
"Фуллскрин":
![image](https://cloud.githubusercontent.com/assets/6878143/5519953/60fde160-897c-11e4-8a55-a5d47d8e5171.png)
Встроенная, с полосами прокрутки:
![image](https://cloud.githubusercontent.com/assets/6878143/5519955/a86186f6-897c-11e4-855d-c926b7da5d72.png)

В итоге как вышло - на анимацию 40 строк кода, на создание `AnimationView`, на борьбу со `ScrollingComposite`'ами и на организацию вызовов `redraw()` - добрых полторы сотни строк.
Зато пока делал, я нашел мега-косяк в движке, который прокрался, когда я делал единые временно-постоянные ресурсы.

**Comment by bogachev-pa** [comment]
Ну вообще, РДО (русскими буквами) это язык, а IDE для разработки на старом РДО это `RAO-studio`. RDO (английскими буквами) это вообще немного странная аббревиатура. 
А еще лично у меня `X` ассоциировалась с `Xtext`, а не с глобально новой версией.

Я тогда пока буду использовать название `rdo-x` в проекте, а там посмотрим.

Анимация выглядит круто. Она же векторная, да?

**Comment by k-alexandrovsky** [comment]
Нет, это обычный отрисовщик SWT, просто он со сглаживанием и с альфа-блендом, поэтому выглядит довольно приятно. Вообще я хочу сделать в будущем фишку с масштабированием (зумом) анимации, то есть делать ее по сути векторной. При этом пользователю ничего не придется менять. Нужно просто пересчитывать все координаты в пропорции от указанного пользователем размера фрейма к реальному зазумленному. Из-за целочисленного округления пикселей картинку будет колбасить, конечно, но тут уж что поделать. Либо изощренный вариант - добиваться хорошей картинки через преобразование в духе 130% = 200% честной умноженной отрисовки плюс последующее сжатие каким нибудь фильтром Ланцоша.

**Comment by bogachev-pa** [comment]
Я тут еще подумал насчет названия. Всё-таки неправильно использовать `RDO` и по отношению к плагину, и по отношению у языку. И аббревиатуру `RDO` тоже не хочется использовать, это же по сути транслит, как-то несерьезно.

Мне кажется должно быть что-то в таком духе:
Название плагина: `rao-x`, где `x` не имеет отношение к версии.
Версия РДО (языка!), с которой работает плагин: `рдо 3.0` (мы ведь нарушаем обратную совместимость, так?) или, если мы хотим ребрендинг, то, например, `rao 1.0` или, если делать их синонимами, то `рдо 3.0 == rao 3.0`. Но только не `rdo`.

**Comment by k-alexandrovsky** [comment]
Пусть будет `RAO 3`, а по-русски `РДО 3`. Цифра три отвлечет на себя внимание, и с ней будет звучать внушительнее.

<шутка> Ну или `RAO R3LOADED` </шутка>

**Comment by aurusov** [comment]
> Мне в ответ - "аа, снова парикмахерская"

Это говорит не только о том, что легче запомнить. Но и об уровне культуры. Из-за подобных случаев точно не надо ничего менять. Если и менять, то на `Barber 3`.

**Comment by aurusov** [comment]
Название языка и метода моделирования - `РДО`, по английски `RAO`. Тут ничего менять не надо. `RDO` - нет такого.
Название системы моделирования:
- `RAO-simulation` - использовать нельзя по договоренности Емельянова с Ясиновским
- `RAO-studio` - название существующей системы
- `RAO-XT` - предлагаю использовать как рабочее название

Надо двигаться в оформлении курсовых и дипломов. Тему предлагаю закрыть. Вернуться к теме ребрендинга конечно можно. Только без фанатизма и чтобы не блочило курсовые с дипломами.

**Comment by k-alexandrovsky** [comment]
Хорошо, тогда название в целом `RAO-XT`, а все пакеты переименовать в виде `ru.bmstu.rk9.raoXt.*` (не уверен насчет комбинации строчных-заглавных букв, но дефисы точно нельзя использовать в имени пакета)

**Comment by aurusov** [comment]
Тогда лучше `raoxt`
Еще думаю про изменение домена, но пока не определился
http://www.rdostudio.com/
