### ISSUE TITLE
Провести замеры скорости

### ISSUE THREAD

**Issue by aurusov** [aurusov/raox#3]
Нужно замерить сокрости работы модели простейшей СМО на РДО и Эклипсе. Подбери условие остановки, чтобы модель работала 10-60 секунд. Запустить лучше по три раза. Статистику давай прямо сюда.

**Comment by k-alexandrovsky** [comment]
Сделал ту же модель, но с остановкой на 5040000 минутах. При этом я отключил в РДО сбор статистики с показателей, раньше я о нем как то не подумал. И результаты печальны, это даже не в пять раз(

| РДО с форума | [Моя версия](http://pastebin.com/FcRR6dre) с консультации | Та же со статическими choice from'ами | [Новая версия](http://pastebin.com/ussZf2ij) с _минимальным числом_ new |
| --: | --: | --: | --: |
| 24 с | 20,7 с | 20,8 с | 28 с |

Единственное объяснение этому - дженерики. Они еще медленнее new. Каждый раз, когда мне нужно обернуть поведение объекта отдельно от того, кто его хранит, я делаю интерфейс. Если функции, переопределяемые в интерфейсе должны знать о структуре каких то классов, появляются дженерики. Что то в них пробрасывается потом (у меня в варианте со статическими choice-ами туда закидывался текущий паттерн (или набор ресурсов в случае с новой архитектурой в новой модели, это, видимо, и не важно)).
Выходит, что плюсы со своими шаблонами уделывют джаву именно благодаря шаблонному копипасту, выполняемому компилятором. А тут просто более безопасное приведение типов со статическим анализом. Это удобно для программиста, но на производительности сказывается весьма и весьма.

Мое скромное предложение в связи со сложившейся ситуацией - генерировать кучу копипасты, в которой не будет ни одного дженерика. Потому что мы можем. А код будет громоздким, некрасивым, зато быстрым.

**Comment by aurusov** [comment]
Интересная ситуация. Особенно в свете того, что в рантайме особых шаблонов нет, есть только "медленные" калки. Давай никаких специальных шагов по оптимизации предпринимать не будем. Убрать new до choice from - это одно. Это даже не оптимизация, а просто проектное решение. С оптимизацией посмотрим позже. Тут без профилятора делать нечего. Предлагаю сейчас остановиться.

PS: по сколько раз замерял каждый результат ? в таблице уже среднее ?

**Comment by k-alexandrovsky** [comment]
да, все прогоны дают ±0.1 секунду, пробовал раз по пять, среднее вычислил так, на глаз

**Comment by k-alexandrovsky** [comment]
И исходный код есть в таблицах. Мне как, переписывать генератор на версию с интерфейсом конвертера?

**Comment by aurusov** [comment]
Да, даже если она медленнее.

**Comment by k-alexandrovsky** [comment]
Еще одна удивительная новость. Я отключил вывод в stdout сообщений о событиях-паттернах, и оно ускорилось. В **_116**_ раз. Было 28 секунд, стало 0,24. Думаю, надо как то избавляться от stdout, создавать свое окошко трассировки, и пытаться максимально оптимизировать вывод в него

**Comment by aurusov** [comment]
Не понял, где было окно stdout ? Надо отключить весь вывод нафиг. И на экран и в файл. Прошу обновить таблицу.

**Comment by k-alexandrovsky** [comment]
Окно stdout - это вот
![](http://i.gyazo.com/e4734c29ac9dad1348067117e36590a9.png)

Я по каждому чиху вызывал

``` java
System.out.println("...")
```

Что было большой-большой ошибкой

В итоге расклад такой

| Режим | РДО с форума | [Эклипс](http://pastebin.com/ussZf2ij) |
| --: | --: | --: |
| С трассировкой (условно) | 47,3 с | 23,3 с |
| Без трассировки | 26,3 с | **0,255 с** |

Базовая проверка с помощью watch_par и выводом в консоль параметра в моем случае. Результат одинаковый (парикмахер обслужил 84000 клиентов)

**Comment by aurusov** [comment]
В режиме с трассировкой сравнивать просто некорректно. Из итоговых результатов просто убери. Ты можешь выложить полную таблицу по всем 4-м версиям ?

**Comment by k-alexandrovsky** [comment]
Итоговая

| РДО с форума | [Моя версия](http://pastebin.com/FcRR6dre) с консультации | Та же со статическими choice from'ами | [Новая версия](http://pastebin.com/ussZf2ij) с _минимальным числом_ new |
| --: | --: | --: | --: |
| 26,3 с | 0,25 с | 0,23 с | 0,255 с |

**Comment by aurusov** [comment]
Во, другое дело. Закрываю таску.
