### ISSUE TITLE
Написать DPT search

### ISSUE THREAD

**Issue by k-alexandrovsky** [aurusov/raox#4]
Поиск решения на графе состояний, вот это всё.

**Comment by k-alexandrovsky** [comment]
@aurusov 
Начал думать о реализации, и сразу же столкнулся с проблемой. В РДО при поиске на графе каждая вершина - это клон всей структуры модели (я сразу вспомнил про проблему, которая возникла после моего курсача со списками ресурсов, правда, тогда я не понимал, о каком таком клонировании идет речь). Я пытался придумать варианты, как этого можно избежать, но ничего не смог придумать (создавать копии лишь тех ресурсов, что были изменены, к примеру, но временные ресурсы превращают эту задачу в крайне трудоемкую; как то хранить дельты, цепочки конвертеров, вводить обратные конвертеры, если мы захотим вернуться на состояние назад, и так далее, это все крайне проблематично).
В итоге надо копировать все ресурсы.
Решение мне видится очень простым. Всеми ресурсами владеет `ResourceManager`, и списки ресурсов мы просим у него. В таком случае, нам нужно ввести механизм установки _временного_ менеджера для каждого типа ресурса, чтобы все запросы на получение ресурсов, идущие через `getManager()`, приводили к временному менеджеру. Вот его мы и будем клонировать. А у ресурса будут методы `assignTemporaryManager(...)` и `clearTemporaryManager()`, которые мы будем дергать в процессе DPT search и по завершении оного соответственно. Последнее препятствие, которое при такой схеме остается, это постоянные ресурсы. Сейчас мы их храним как `HashMap` у менеджера и как статические поля класса одновременно. Доступ производится средствами java как раз к ресурсам-атрибутам. 

Теперь вопрос - как будет правильнее:
1. Убрать статики в классе типа ресурса и оставить лишь доступ через мапу `<K = Имя_ресурса, V = Ресурс>` (тут вопрос по скорости доступа, хотя у нас хэш высчитывается лишь в начале работы, и так как постоянные ресурсы не добавляются, доступ должен быть быстрым по уже установившемуся хэшу)
2. Учить менеджера менять наборы постоянных ресурсов в статических атрибутах. Тут проблема в том, что менеджер не в курсе, что именно он хранит. Он знает лишь тип, но не структуру, поэтому это будет еще один интерфейс, который будет знать, как подменить ресурсы в статиках ресурсами из клонированной мапы

**Comment by aurusov** [comment]
1. Намного важнее продумать структуру программы. Затачивать её под оптимизацию сейчас не стоит.
2. Можно и так, не могу оценить сходу.

Давай ты сначала нарисуешь схему классов, которые реализуют БД. В идеальном мире надо завести объект `DataBase` с методом `clone()`. Предлагаю начать с того, чтобы текущую БД выделить в отдельный объект.

PS: DPT search для курсача неважен.

**Comment by k-alexandrovsky** [comment]
Хорошо. На досуге подумаю над организацией DataBase-класса. А еще очень хочется реализовать lazy copying, т.е. клонирование ресурса лишь при изменении. С точки зрения памяти эта схема ну очень хороша. И тут само собой надо перевести параметры ресурсов на схему getter-setter, где setter будет оповещать DataBase о том, что он что-то поменял. Это в любом случае придется сделать, потому что без этого вменяемый трассировщик тоже не напишешь. Как только я ухвачусь за итоговую концепцию и напишу какую то основу с этими оповещениями, тогда и ленивое клонирование написать не составит труда, а там и dpt search почти готов, можно сказать. Пусть он не важен для курсача, мне просто хочется прощупать алгоритмическую часть, скажем так

**Comment by aurusov** [comment]
Если ты про [COW](http://en.wikipedia.org/wiki/Copy-on-write), то это очень сложно. Я как-то писал это для C++. Да ну такое в баню. Давай после того, как курсач будет готов. Что-то ты разбежался, я уже волноваться начинаю.

**Comment by k-alexandrovsky** [comment]
Я наконец то допилил модель пятнашек, написав для этого алгоритмические типы функций, и проверил поиск без решения и с решением.
В решаемых ситуациях решение находится, одинаковое, оптимальное, в общем, все работает.

Замеры поиска в ширину на нерешаемой ситуации **без** сравнения вершин (бесконечный поиск):

| Симулятор | Время работы | Порожденных вершин | Потребление RAM | Kb/вершину |
| --: | --: | --: | --: | --: |
| Старая РДО с форума | ~20с | 50.000 | 550Mb | 11,3 |
| rdo-xtext | ~20с | 1.250.000 | 1000Mb | 0,82 |

Результат таков именно благодаря этому механизму клонирования ресурсов лишь в результате их изменения. С какой то стороны это и есть copy on write, который, как оказалось, имеет крайне простую реализацию в получившейся архитектуре.

**Comment by aurusov** [comment]
А почему кол-во порожденных отличается ?

**Comment by k-alexandrovsky** [comment]
Это бесконечный и бессмысленный поиск на нерешаемой ситуации с compare tops = no. Был бы yes, он бы все 360 состояний просмотрел, и вышел бы из поиска с невыполненной dpt.

**Comment by aurusov** [comment]
Очевидно. Вопрос был не про это.

**Comment by k-alexandrovsky** [comment]
Тогда я не очень понял вопрос. Просто быстрее работает, я хотел показать, насколько быстрее.

**Comment by aurusov** [comment]
Ты в коде писал остановку по достижению `50.000/1.250.000` ? Объясни, откуда они взялись.

**Comment by k-alexandrovsky** [comment]
Нет. Для РДО запустил по секундомеру прогон, остановил по прошествии 20 секунд. В РДО в конце трассировки есть цифра порожденных вершин, ее и взял, при этом самой трассировки для чистоты эксперимента не было. Память посмотрел в виндовом диспетчере. У себя я в коде просто добавил условие останова поиска по времени. Вывел размеры списков, сложил. Память так же. Понятно, что на абсолютную чистоту эксперимент не тянет, но мне просто хотелось получить примерные цифры.

**Comment by aurusov** [comment]
Теперь понятно.
