### ISSUE TITLE
Создание контексто-зависимого компилятора выражений

### ISSUE THREAD

**Issue by k-alexandrovsky** [aurusov/raox#5]

**Comment by k-alexandrovsky** [comment]
to @aurusov
Возникла проблема c инкрементами. Дело в том, что доступ к параметрам ресурсов сейчас реализуется путем работы с парой getter-setter. Иное мне не представляется возможным, потому что трейсер, потому что работа с контекстом базы данных, и мало ли еще что в будущем. Java, к сожалению, не шарп, тут нельзя неявно вызывать сеттеры через простое присвоение. Поэтому проблема в следующем:
Выражение `Ресурс.параметр++;` спокойно превращается в `Ресурс.set_параметр(Ресурс.get_параметр() + 1);`. Но это если оно и есть statement целиком. Выражение `if(Ресурс.параметр++ > 10)`, каким бы странным оно ни было, без сеттеров вполне легально, а с ними неизвестно в какой код должно вылиться.
Навскидку я могу предложить два решения, первое чуть изобретательнее, второе проще/быстрее.

1) Прямо в коде писать примерно следующее:

``` java
if(new rdo_lib.ReturnableInt(){
        @Override
        public int get()
        {
                int copy = Ресурс.get_параметр(); 
                Ресурс.set_параметр(Ресурс.get_параметр() + 1);
                return copy;
        }.get() > 10)
        // IF BODY //
```

Итог - возня с объектами.

2) Каждому интовому параметру в типе ресурса сделать хитрый сеттер с присвоением, который вернет копию. А префиксные операции делаются и так, это просто сеттер, который возвращает присвоенное значение дальше. У меня это уже так сделано.
Итог - еще более распухший (не сильно, впрочем) класс типа ресурса.

**Comment by aurusov** [comment]
В текущей версии РДО такое возможно написать в **условии** ?

**Comment by k-alexandrovsky** [comment]
Проверил, нельзя. В РДО инкремент это не expression вовсе, а statement. Хотя хотелось как то поуниверсальнее сделать. Просто у меня пример плохой. Я думал, что хотя бы выражение

```
integer a = 0;
a = Ресурс.параметр++;
```

легально. Оказывается, и оно нет.
Ведь для локальных переменных можно было бы получить такое нахаляву за счет возможностей java.

**Comment by aurusov** [comment]
В том-то и дело. В текущем РДО возможно

```
Ресурс.параметр++;
```

Других примеров не знаю. В любом случае лучше думать не ресурсом, а **операцией** с параметрами. Вот [пример](http://stackoverflow.com/a/4445969) реализации.

**Comment by k-alexandrovsky** [comment]
Тогда предлагаю сделать для каждого параметра сделать пару сеттеров:

``` java
public ParameterType set_ParameterName(ParameterType value) // это уже есть
{
        this.ParameterName = value;
        return value;
}

public ParameterType set_ParameterName_after(ParameterType value)
{
        ParameterType copy = this.ParameterName;
        this.ParameterName = value;
        return copy;
}
```

Вроде как по скорости/памяти никто особо не пострадает, а инкременты таким образом можно будет сделать элементарно, ну и мало ли еще какие хитрые и очень нужные конструкции в будущем.
Для энумов придется чуть посложнее код написать (хотя с этим и `Object::clone()` должен справиться), потому что они не immutable, либо просто убрать у них такую возможность.

**Comment by aurusov** [comment]
Можно.

**Comment by k-alexandrovsky** [comment]
Сделал локальный и глобальные контексты в начальном виде, научил некоторые типы выражений искать enum'ы. Инкременты работают.
Много где вылезут баги, конечно, много где придется дописывать и расширять контексты, но начальная задача, думаю, выполнена. Парикмахерская с временными ресурсами из шаблонного проекта работает и компилируется с одним лишь изменением: надо дописать одну точку с запятой в DPT. Но эта задача у меня уже стоит, в ближайшее время ей займусь.
