### ISSUE TITLE
Написать старый ГПСЧ, совместимый с РДО

### ISSUE THREAD

**Issue by k-alexandrovsky** [aurusov/raox#6]
Цель - точное совпадение трассировки со старой РДО и логами моделей в системе автотестирования.

**Comment by k-alexandrovsky** [comment]
@aurusov 

Как оказалось, все решалось очень и очень просто:

``` java
package rdo_lib;

public class RDOLegacyRandom
{
    private long seed = 0;

    public RDOLegacyRandom(long seed)
    {
        this.seed = seed;
    }

    public void setSeed(long seed)
    {
        this.seed = seed;
    }

    public double nextDouble()
    {
        seed = (seed * 69069L + 1L) % 4294967296L;
        return seed / 4294967296.0;
    }
}
```

Результат полностью соответствует ожиданиям:
![rdo_random](https://cloud.githubusercontent.com/assets/6878143/2706477/efee97da-c491-11e3-992b-cf934664827a.png)

**Comment by aurusov** [comment]
Круть. Округлить осталось.

**Comment by k-alexandrovsky** [comment]
Округлять java, я думаю, умеет, просто трассировку я пока не писал, это будет отдельной большой задачей.
