### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [aurusov/raox#611]
Hello Raox team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the Raox project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by bogachev-pa** [comment]
Hi Tamás! Thank you for reaching out. Here you go:
```
<tr>
    <td><a href="https://github.com/LeKaitoW/raox">Rao X</a></td>
    <td>This project is an implementation of RAO modelling language in Eclipse, using Xbase.</td>
    <td>MIT</td>
    <td>Simulation system</td>
    <td>Andrey Urusov, Pavel Bogachev, Kirill Alexandrovsky, Olga Zudina, Alexey Chernov and other contributors.</td>
</tr>
```

**Comment by miklossy** [comment]
Thank you @bogachev-pa !

**Comment by miklossy** [comment]
The `Rao X` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).

**Comment by bogachev-pa** [comment]
Thank you, Tamás, that's nice to see.
