### ISSUE TITLE
Написать функции

### ISSUE THREAD

**Issue by k-alexandrovsky** [aurusov/raox#7]

**Comment by k-alexandrovsky** [comment]
Еще один вопрос по старому синтаксису. `Calculate_if` реализовывать? Просто по нему в текущей справке ничего.
Там синтаксис `Calculate_if (условие) Имя_функции = Выражение`
полностью ли соответствует `if (условие) return Выражение`?

И еще возникла проблема с `=`/`==`. Все старые выражения (`Select`, `Calculate_if`...) позволяют писать одно равно вместо двух. Мне вводить такую поддержку? Я могу сделать альтернативную ветку в грамматике выражений, где можно писать одно равно. Этой веткой будут пользоваться выражения, у которых не предусмотрено присвоение.

**Comment by aurusov** [comment]
- Calculate_if - странно, что он еще есть. Думал, что после конвертера оно было удалено. Поддержки не надо. Проверь что там в C++ коде, приведи ссылку. Если оно там есть, то поставь задачу на удаление.
- Давай только двойное. Приведи ссылку на C++ код, где есть одинарное.

**Comment by k-alexandrovsky** [comment]
Так, я был введен в заблуждение старой версией РДО (которая идет с game5) по обоим пунктам. Вопрос снимается.

**Comment by k-alexandrovsky** [comment]
Доделал листовые функции. Сначала хотел как нибудь хитро организовать всякие хеши-мультихеши для значений параметров, но так и не придумал оптимального решения, да и время на высчитывание хеша и сериализацию всех параметров может уйти немаленькое, в итоге сделал самым простым способом. Да и в РДО вроде также.
<br>
Source:

```
$Function aaa : string = ""
$Type = list
$Parameters
    a : integer
    b : real
    c : such_as Детали.Вид
$Body
    1 1.0 вал        = "рыба"
    2 0.5 крыльчатка = "селедка"
$End
```

<br>
Gen:

``` java
package rob5;

public class aaa
{
    public static String evaluate(Integer a, Double b, rob5.Детали.Вид_enum c)
    {
        if
        (
            a == 1 &&
            b == 1.0 &&
            c == rob5.Детали.Вид_enum.вал
        )
            return "рыба";

        if
        (
            a == 2 &&
            b == 0.5 &&
            c == rob5.Детали.Вид_enum.крыльчатка
        )
            return "селедка";

        return "";
    }
}
```

**Comment by aurusov** [comment]
Вполне
